### ISSUE TITLE
Project role to become an ontology field

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#855] opened 2019-03-04 14:11 UTC
**For which schema is a change/update being suggested?**

`project_role` should be an ontology rather than an enum?

ArrayExpress use this term https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0002012

We would need:

Add:
- data wrangler
- pathologist
- technician
- principal investigator
- co investigator
- clinician
- experimental scientist
- computational scientist
- administrator

Substitute:
- external curator -> curator

Remove:
- other

**Comment by malloryfreeberg** [comment] 2019-03-07 14:02
@daniwelter if we would like to suggest adding some of our terms, can we list them in this ticket with the requested term and description? Or should be make the request in another repo?

**Comment by daniwelter** [comment] 2019-03-07 14:06
Please put a separate request into the ontology repo. It makes it easier for me to track all the ontology additions that are needed.

**Comment by malloryfreeberg** [comment] 2019-03-07 14:22
Can you link to that repo here so I don't have to try to remember :)

**Comment by daniwelter** [comment] 2019-03-07 14:33
Srsly?? https://github.com/HumanCellAtlas/ontology

**Comment by lauraclarke** [comment] 2019-03-11 18:43
Quick comment, clinician and consultant are not synonymous in the UK health system. We should confirm that it is an appropriate term to use as someone who hasn't reached that stage in their medical career might not want that term and might create problems

**Comment by malloryfreeberg** [comment] 2019-03-12 09:31
RE: computational scientist -> data analyst

I think I would rather add "computational scientist" than use "data analyst" here. I don't see a definition for this term in the ontology, but some Googling shows the "data analyst" term is often used in reference to business and problem-solving, not so much in science or as a way to answer hypotheses. Wikipedia's definition of [computational scientist](https://en.wikipedia.org/wiki/Computational_scientist) is:

> A computational scientist is a person skilled in scientific computing. This person is usually a scientist, an engineer, or an Applied mathematician who applies high-performance computing and sometimes cloud computing in different ways to advance the state-of-the-art in their respective applied disciplines; physics, chemistry, social sciences and so forth. Thus scientific computing has increasingly influenced many areas such as economics, biology, law, and medicine to name a few. Because a computational scientist's work is generally applied to science and other disciplines, they not necessarily trained in Computer science specifically (though concepts of computer science are often used). Computational scientists are typically researchers at academic universities, national labs, or companies.

**Comment by lauraclarke** [comment] 2019-03-12 09:37
It would be good to be able to see the definition of these terms, the ols website doesn't seem to provide them @daniwelter do you know where we can find them

**Comment by daniwelter** [comment] 2019-03-12 09:43
If they're not in OLS, they're not in the ontology but I can add them if there's anything specific we're looking for.

For the record, I don't agree with any of the synonyms proposed above expect perhaps external curator as a synonym for curator. All the other terms should be terms in their own right.

**Comment by lauraclarke** [comment] 2019-03-12 09:59
@daniwelter I can't find a definition for consultant through which is in OLS https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001732

**Comment by daniwelter** [comment] 2019-03-12 10:15
Yes, as I said, if the definition isn't in OLS, the term doesn't have a definition in the ontology. It's not very good practice to add ontology terms without definition but there are 1000s like that anyway, especially from the early days of EFO.

**Comment by malloryfreeberg** [comment] 2019-03-12 11:49
Instead of "Human Cell Atlas wrangler", maybe we just go with "data wrangler"?

**Comment by malloryfreeberg** [comment] 2019-03-13 14:08
Suggested new terms/definitions to add (will put a separate request in the ontology repo):

1. **data wrangler** - A person who converts data into a usable form with the intent of making the data more usable and valuable for a variety of purposes such as use in downstream automated or semi-automated tools. (no citation)
1. **pathologist** - A person who studies the causes and effects of diseases, especially one who examines laboratory samples of body tissue for diagnostic or forensic purposes. ([citation](https://en.oxforddictionaries.com/definition/pathologist))
1. **technician** - A person employed to look after technical equipment or do practical work in a laboratory. ([citation](https://en.oxforddictionaries.com/definition/technician))
1. **principal investigator** - The principal or lead person who carries out a formal inquiry or investigation. ([citation with modification](https://en.oxforddictionaries.com/definition/investigator))
1. **co investigator**- One of two or more persons who carries out a formal inquiry or investigation. ([citation with modification](https://en.oxforddictionaries.com/definition/investigator))
1. **clinician** - A doctor having direct contact with patients rather than being involved with theoretical or laboratory studies. ([citation](https://en.oxforddictionaries.com/definition/clinician))
1. **experimental scientist** - A scientist who performs experiments in a laboratory equipped with appropriate plumbing, ventilation, and equipment to allow for hands-on scientific research and experimentation. ([citation with modification](https://www.merriam-webster.com/medical/wet%20lab))
1. **computational scientist** - A scientist who performs experiments in a laboratory for making computer simulations or for data analysis especially by computers. ([citation with modification](https://www.merriam-webster.com/medical/dry%20lab))
1. **consultant** - A person who provides expert advice professionally. ([citation](https://en.oxforddictionaries.com/definition/consultant))
1. **data curator** - A person who organizes, integrates, and annotates data collected from various sources in order that the value of the data is maintained over time and the data remains available for reuse and preservation. ([citation with modification](https://en.wikipedia.org/wiki/Data_curation))

**Comment by malloryfreeberg** [comment] 2019-03-13 14:09
@hewgreen @lauraclarke @daniwelter please let me know if you'd like any edits to the above terms by **Friday Mar 15**. Afterwards I'll convert the consensus terms to a formal request in the ontology repo.

**Comment by willrockout** [comment] 2019-03-13 21:11
@malloryfreeberg I feel data wrangler and data curator are the same things. The rest looks good to me!

**Comment by zperova** [comment] 2019-03-13 23:28
What happened to the “administrator” role?

**Comment by malloryfreeberg** [comment] 2019-03-14 09:30
> What happened to the “administrator” role?

Oops! Dropped that one. Will add back.

**Comment by malloryfreeberg** [comment] 2019-03-14 09:34
> @malloryfreeberg I feel data wrangler and data curator are the same things. The rest looks good to me!

@daniwelter do you have thoughts on whether the curator and wrangler definitions are too close to be considered two separate ontology terms?

**Comment by lauraclarke** [comment] 2019-03-14 09:35
@malloryfreeberg I know I am not who you asked but I suspect sticking with curator for both is a good idea

**Comment by malloryfreeberg** [comment] 2019-03-14 10:03
Dani agrees as well.

**Comment by claymfischer** [comment] 2019-03-14 19:11
Curator and wrangler are two fairly defined roles, from my perspective.

A _wrangler_ interacts with labs and often handles unprepared data to prepare for submission to a database. They require good social skills.

A _curator_ tends to be in a role where they do not work with labs directly, but rather with publications to extract information and primarily works with data already submitted and in a database.

**Comment by lauraclarke** [comment] 2019-03-14 19:20
I suspect the ArrayExpress curators who work closely with publication authors to accurately reflect their data in the archive would disagree with important parts of that distinction

I am also not sure if that distinction is helpful from the perspective of anyone external using these labels for looking at who has been responsible for what in the context of HCA submissions using the metadata

**Comment by daniwelter** [comment] 2019-03-15 16:50
All terms apart from data wrangler added/updated in EFO. The next EFO release will be on Monday and I will do an HCA-internal release in the next couple of weeks, subject to resolving some unrelated blocking ontology issues.

**Comment by zperova** [comment] 2019-03-18 11:15
I think a wrangler and a curator should be two separate terms. As the data contributors work with wranglers, and not curators, substituting wrangler for curator makes it confusing in my opinion.

**Comment by lauraclarke** [comment] 2019-03-18 13:18
Sounds like we need to have an in-person discussion about this.

An important issue to consider is what is the downstream use case for this role field. In the context of those downstream use cases, is it useful to distinguish between curator and wrangler?

In the DCP the wranglers work with contributors, in other contexts such as the Gene Expression Atlas, curators work with paper authors, I would love to hear concrete reasons why in the general sense, they are jobs with sufficiently limited overlap in responsibilities that different terms are useful.

**Comment by zperova** [comment] 2019-03-18 13:58
If this information will be only for internal use, then I think it is fine to keep wrangler and curator the same, but if this will ever be contributor-facing, I think it will be confusing for them not to see "their wrangler" in the list as wrangler - since this is how we call ourselves and how they refer to us in all our communications.

**Comment by malloryfreeberg** [comment] 2019-04-11 12:55
The two issues referencing this issue (#893 and #894) are done.

**Closed by malloryfreeberg** 2019-04-11 12:55 UTC
Labels: content
