### ISSUE TITLE
Describe how to represent technical and biological replicates in the metadata spreadsheet.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#484] opened 2018-08-08 10:17 UTC
Describe how to represent technical and biological replicates in the metadata spreadsheet.

**Comment by hewgreen** [comment] 2018-09-18 16:00
duplicate of https://app.zenhub.com/workspace/o/humancellatlas/ingest-central/issues/174

**Closed by hewgreen** 2018-09-18 16:00 UTC
Labels: documentation
