### ISSUE TITLE
Review HCA repositories and verify that the list of readers/writers is following principle of least access

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#868] opened 2019-03-05 21:35 UTC
The HumanCellAtlas GitHub teams have been restructured.
To ease the transition to this structured world, everyone is currently in a team called "HCA" that has WRITE access to all repos.  We want to move away from this.

Each component team lead needs to audit the GitHub teams that have access to their repos.
Ensure only appropriate teams (e.g. CZI, UCSC, etc) have write access to your component's repos.
Ensure that you approve of any collaborators.
Then remove access from team HCA.

**Comment by malloryfreeberg** [comment] 2019-04-02 23:06
Related to #866

**Comment by stahiri** [comment] 2019-05-07 13:08
@zperova - I believe you're the appropriate owner for this task; please reassign if not!

**Comment by zperova** [comment] 2019-05-07 14:00
@stahiri I am not. @malloryfreeberg has been looking into it.

**Comment by malloryfreeberg** [comment] 2019-05-07 16:08
@stahiri I have confirmed all members of the metadata-updates team are the people who should have write access to this repo. Am I supposed to now remove access from team HCA? Not sure how to do this...

**Comment by malloryfreeberg** [comment] 2019-05-30 14:54
@stahiri If the metadata-schema repo teams section looks like this:

<img width="750" alt="Screen Shot 2019-05-30 at 15 52 58" src="https://user-images.githubusercontent.com/10993501/58641423-11466280-82f3-11e9-8dd5-02bf1e1212e5.png">

And I have confirmed only the appropriate people are in the metadata-updates team, is this enough to satisfy this ticket? I didn't actually have to remove an "HCA" group.

**Comment by stahiri** [comment] 2019-05-30 15:56
Yes, that satisfies this need. Thank you!

**Closed** 2019-05-30 21:41 UTC
Labels: done, task
