### ISSUE TITLE
Investigate ensuring integers stay integers in metadata

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1218] opened 2020-01-29 16:52 UTC
When a wrangler enters an integer value in a spreadsheet, sometimes this gets converted into a float value. 

One example is from the TissueSensitivity dataset tsv file in the `sequencing_protocol.10x.pooled_channels` field which has been converted from `4` to `4.0` as discovered in https://github.com/HumanCellAtlas/hca-data-wrangling/issues/355#issuecomment-579821610

This ticket is to figure out how this happens and come up with a solution to ensure the fields that should be kept as integers stay that way through the metadata entry and ingest process.

**Current ideas for what could be happening:**
* When a spreadsheet is imported using openpyxl the data format for that field is converted to a float value due to some underlying formatting in the excel file which is invisible to the wrangler

**Potential solutions that need to investigated:**
* changing the 'type' for all fields that should be integers to 'integer' instead of 'number'

**Comment by MightyAx** [comment] 2020-02-27 09:57
Tested: Formatting the cells in excel, using a Number format with 0 decimals places fixes the issue when importing.
![Screenshot 2020-02-27 at 09 56 50](https://user-images.githubusercontent.com/13031259/75433193-7cd36400-5947-11ea-8114-96656052acc1.png)

**Comment by mshadbolt** [comment] 2020-02-28 08:55
Thanks Alexie. We probably need a better solution long term than expecting a contributor/wrangler to check the formatting of every numeric column in a spreadsheet. 

So that I can understand better, does the importer pay attention to the `type` field in the schema? So if we made sure that all fields that need to be integers have `integer` as the type then the importer could cast the value as the correct type?

**Comment by MightyAx** [comment] 2020-02-28 09:47
A rough outline of the order of operations:
1. Get raw data from spreadsheet.
2. Use Metadata Schema decide how to convert raw data to desired format.
3. Add data to JSON object or add error to error list.

Our problem is occurring in step 1, the openpyxl library will provide us the data as whatever type is encoded into the spreadsheet. This is awkward because we can't trust the "base value" we read out of the excel, and the changes we make to turn it back could be wrong if the data was intended to be like that.

Investigation ongoing.

**Comment by ESapenaVentura** [comment] 2021-06-10 11:01
This was disclosed as a not-metadata issue but rather a problem with excel conversion. If this comes again we can open tickets in the proper places. Closing!

**Closed by ESapenaVentura** 2021-06-10 11:01 UTC
Labels: protocol
